import {
  Dashboard,
  Shipments,
  Orders,
  Pickup,
  Hub,
  Sorting,
  Transfer,
  Route,
  Riders,
  Vehicle,
  Delivery,
  Ndr,
  Returns,
  Cod,
  Sellers,
  Customers,
  Analytics,
  Sparkle,
  Geofence,
  Settings,
} from '../icons'

// Single source of truth for the sidebar, breadcrumbs, ComingSoon
// copy, and the command palette's page search -- one array, four
// consumers, nothing hand-duplicated between them.
export const navConfig = [
  {
    group: 'Overview',
    items: [
      { key: 'command-center', label: 'Command Center', path: '/', icon: Dashboard, status: 'ready' },
    ],
  },
  {
    group: 'Fulfillment',
    items: [
      {
        key: 'shipments',
        label: 'Shipments',
        path: '/shipments',
        icon: Shipments,
        status: 'phase2',
        description: 'Every shipment as a searchable, filterable digital twin — full lifecycle timeline from order to delivery, virtualized for enterprise-scale volume.',
        bullets: ['Shipment digital twin with event timeline', 'Virtualized table for 1M+ rows', 'Drill down to seller, customer, rider, hub'],
      },
      {
        key: 'orders',
        label: 'Orders',
        path: '/orders',
        icon: Orders,
        status: 'phase2',
        description: 'Order-level view across sellers, items, and fulfillment status, one layer above individual shipments.',
        bullets: ['Order → shipment relationship view', 'Cancellation and split-order tracking', 'Seller-side order health'],
      },
      {
        key: 'pickup',
        label: 'Pickup',
        path: '/pickup',
        icon: Pickup,
        status: 'phase2',
        description: 'First-mile pickup scheduling and completion tracking, seller by seller.',
        bullets: ['Pickup SLA by seller', 'Failed pickup reasons', 'Rider pickup assignment'],
      },
    ],
  },
  {
    group: 'Network Ops',
    items: [
      {
        key: 'hubs',
        label: 'Hubs',
        path: '/hubs',
        icon: Hub,
        status: 'phase2',
        description: 'Full hub operations module — capacity, staffing, and a network-wide health-score leaderboard, expanding on the Command Center map.',
        bullets: ['Hub health score breakdown', 'Aging shipment tracking', 'Staff productivity'],
      },
      {
        key: 'sortation',
        label: 'Sortation',
        path: '/sortation',
        icon: Sorting,
        status: 'phase2',
        description: 'Inbound sort-center throughput and pending-sort aging, per hub.',
        bullets: ['Sort throughput by shift', 'Pending sort aging', 'Misroute rate'],
      },
      {
        key: 'linehaul',
        label: 'Linehaul',
        path: '/linehaul',
        icon: Transfer,
        status: 'phase2',
        description: 'Hub-to-hub trunk movement — trip status, load factor, and transit delay tracking.',
        bullets: ['Trip status board', 'Load factor by trip', 'Transit delay root cause'],
      },
      {
        key: 'routes',
        label: 'Routes',
        path: '/routes',
        icon: Route,
        status: 'phase2',
        description: 'Route planning and AI-recommended rider rebalancing, building on the Command Center exceptions panel.',
        bullets: ['AI route rebalancing recommendations', 'Stop-level ETA', 'Capacity vs. load'],
      },
    ],
  },
  {
    group: 'Fleet & Delivery',
    items: [
      {
        key: 'riders',
        label: 'Riders',
        path: '/riders',
        icon: Riders,
        status: 'phase2',
        description: 'Full rider roster with productivity ranking, COD reconciliation, and AI performance callouts.',
        bullets: ['Performance leaderboard', 'COD collected per rider', 'AI: "operating N% above zone average"'],
      },
      {
        key: 'vehicles',
        label: 'Vehicles',
        path: '/vehicles',
        icon: Vehicle,
        status: 'phase2',
        description: 'Fleet roster and utilization across owned and third-party vehicles.',
        bullets: ['Utilization by vehicle', 'Maintenance status', 'Capacity vs. assigned load'],
      },
      {
        key: 'delivery',
        label: 'Delivery',
        path: '/delivery',
        icon: Delivery,
        status: 'phase2',
        description: 'Out-for-delivery and delivered shipment tracking with live success-rate trends.',
        bullets: ['Delivery attempt tracking', 'Success rate by zone', 'Delivery time distribution'],
      },
      {
        key: 'ndr',
        label: 'NDR',
        path: '/ndr',
        icon: Ndr,
        status: 'phase2',
        description: 'A dedicated failed-delivery command center with AI root-cause analysis, extending the exceptions panel.',
        bullets: ['Failure reason breakdown', 'AI: second-attempt success probability', 'Reattempt scheduling'],
      },
      {
        key: 'returns',
        label: 'Returns',
        path: '/returns',
        icon: Returns,
        status: 'phase2',
        description: 'Reverse logistics from return request through inspection to refund.',
        bullets: ['Return reason breakdown', 'Return-hub aging', 'AI return-probability prediction'],
      },
    ],
  },
  {
    group: 'Finance & Partners',
    items: [
      {
        key: 'cod-finance',
        label: 'COD & Finance',
        path: '/cod-finance',
        icon: Cod,
        status: 'phase2',
        description: 'A financial control center for cash-on-delivery — collection, settlement, and anomaly detection.',
        bullets: ['Settlement aging', 'Rider/hub cash discrepancy detection', 'Seller payable tracking'],
      },
      {
        key: 'sellers',
        label: 'Sellers',
        path: '/sellers',
        icon: Sellers,
        status: 'phase2',
        description: 'A logistics health score per seller — pickup SLA, cancellation, return rate, and NDR in one view.',
        bullets: ['Seller health score', 'Volume and packaging quality', 'Handover time'],
      },
      {
        key: 'customers',
        label: 'Customers',
        path: '/customers',
        icon: Customers,
        status: 'phase2',
        description: 'Customer-side delivery experience — address quality, contactability, and delivery history.',
        bullets: ['Delivery history per customer', 'Address quality signals', 'Contact success rate'],
      },
    ],
  },
  {
    group: 'Intelligence',
    items: [
      {
        key: 'analytics',
        label: 'Analytics',
        path: '/analytics',
        icon: Analytics,
        status: 'phase2',
        description: 'Deep, filterable analytics across every operational dimension — trends, SLA, rider and hub productivity, cost per shipment.',
        bullets: ['Fully filterable by date/hub/seller/rider', 'Cost per shipment and route efficiency', 'Zone-level performance'],
      },
      {
        key: 'ai-intelligence',
        label: 'AI Intelligence',
        path: '/ai-intelligence',
        icon: Sparkle,
        status: 'phase2',
        description: 'The full AI Logistics Commander module — natural-language network Q&A, what-if simulation, and confirmable AI-recommended actions. A lighter version of this lives in the AI assistant panel (top bar) today.',
        bullets: ['What-if scenario simulation', 'Confirmable AI actions', 'Executive summary generation'],
      },
      {
        key: 'network',
        label: 'Network',
        path: '/network',
        icon: Geofence,
        status: 'phase2',
        description: 'Network-wide topology and capacity planning across the full hub graph.',
        bullets: ['Network topology view', 'Capacity planning', 'Zone coverage'],
      },
      {
        key: 'settings',
        label: 'Settings',
        path: '/settings',
        icon: Settings,
        status: 'phase2',
        description: 'Organization, role, and access configuration.',
        bullets: ['Role-based access control', 'Organization settings', 'Notification preferences'],
      },
    ],
  },
]

export const navItems = navConfig.flatMap((g) => g.items)
export const navItemByPath = new Map(navItems.map((i) => [i.path, i]))
